- client/src/App.css
- client/src/components/Card.jsx
- client/src/components/CopyToClipboard.jsx
- client/src/components/Filter.jsx
- client/src/components/IndividualCard.jsx
- client/src/components/css/Card.css
- client/src/components/css/CopyToClipboard.css
- client/src/components/css/Filter.css
- client/src/components/css/IndividualCard.css
- client/src/main.jsx
1. copy to clipboard
2. individual shared contest card
3. minor filter nav changes
> Routing react

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- client/src/components/css/error-page.css
- client/src/components/error-page.jsx
Error Page and it's corresponding CSS file added
> Error Page 

- backend/controllers/contest/DataSyncController.js
- backend/controllers/contest/contestController.js
- backend/index.js
- backend/routes/contest/contestRoutes.js
1) Vanity now fetches from UpComing variable then AllContest Mongodb
2) [BUG] AllContest was not updating (added a try-catch block)
> Backend Fixes

- backend/controllers/user/authController.js
- backend/controllers/user/userDashboardController.js
- backend/controllers/user/userProfileController.js
- backend/models/user/User.js
- client/src/components/Filter.jsx
> codestudio renamed

- backend/models/contest/Contest.js
> vanity lowercase

- backend/index.js
> Separated user and contest functions

- backend/controllers/contest/contestController.js
- backend/index.js
- backend/routes/contest/contestRoutes.js
> Contests route file 

- client/src/components/css/Filter.css
> Minor changes | Css class name changes 

- backend/users/controllers/platforms/codechefUpdater.js
- backend/users/controllers/platforms/codeforcesUpdater.js
- backend/users/controllers/platforms/leetcodeUpdater.js
- backend/users/controllers/userProfileController.js
- backend/users/controllers/userUpdateController.js
- backend/users/models/User.js
- backend/users/services/setUser.js
- backend/users/services/updateUser.js
> User ratings

- client/src/components/Home.jsx
- client/src/components/NewHome.jsx
- client/src/components/ScrollToTop.jsx
Scroll To Top
Fixes #112 
[Screencast from 05-10-23 11:49:29 PM IST.webm](https://github.com/digitomize/digitomize/assets/89705565/ad8124eb-0383-438d-aad7-50f7e0d5ee39)
> Govardhan26

- client/src/components/Filter.jsx
Fix platform label shrink behaviour.
Fixes #131 
> fix(filter): define shrink state

- client/src/components/Button.jsx
- client/src/components/Filter.jsx
- client/src/components/IndividualCard.jsx
[MINOR] Format the code
Removed commented code and formatted code.
Fixes Issue #134
> Fix/134 Removed commented code & formatted the code

- client/src/App.jsx
Added Spinner in discord redirect
> added spinner in discord redirect

- client/src/components/css/Card.css
Fix hovering effect on cards.
Fixes #129 
> fix: hover on cards

- client/src/components/IndividualCard.jsx
> Added to individual page

- client/api.js
- client/src/components/Card.jsx
- client/src/components/IndividualCard.jsx
- client/src/components/Layout.jsx
- client/src/components/Login.jsx
- client/src/components/Signup.jsx
Minor Change , removed unused imports and white space blank lines
> removed extra line spaces and unused import

- client/src/components/Layout.jsx
Alert for introducing Version-2
> Alert for introducing version-2

- client/src/components/Navbar.jsx
refactor: navbar code
fix issue: #186
> refactor: navbar code

- backend/contest/controllers/DataSyncController.js
- backend/contest/controllers/contestController.js
- backend/contest/controllers/platforms/atcoderController.js
- backend/contest/controllers/platforms/codechefController.js
- backend/contest/controllers/platforms/codeforcesController.js
- backend/contest/controllers/platforms/codingninjas_studioController.js
- backend/contest/controllers/platforms/gfgController.js
- backend/contest/controllers/platforms/leetcodeController.js
- backend/contest/models/Contest.js
- backend/contest/routes/contestRoutes.js
- backend/fetchContests.js
- backend/index.js
- backend/package.json
- backend/users/controllers/authController.js
- backend/users/controllers/platforms/codechefUpdater.js
- backend/users/controllers/platforms/codeforcesUpdater.js
- backend/users/controllers/platforms/leetcodeUpdater.js
- backend/users/controllers/userDashboardController.js
- backend/users/controllers/userProfileController.js
- backend/users/controllers/userUpdateController.js
- backend/users/middlewares/authMiddleware.js
- backend/users/models/User.js
- backend/users/routes/userRoutes.js
- backend/users/services/getUser.js
- backend/users/services/setUser.js
- backend/users/services/updateUser.js
Updated the Es5 node version 10 code to Es6 node latest version.
Fixed all types of issues related to ES6.
Since, require uses very old node version, it took a lot of time in fixing whole techstack.
Changed Es5 node version to Es6 node latest.
A lot of server and production error are fixed in this case.
New feature introduced making code more readable andesier to debug.
> Updated ES5 code to ES6.

- backend/users/controllers/leaderboardController.js
- backend/users/routes/userRoutes.js
- client/api.js
- client/src/App.jsx
- client/src/components/NewNavbar.jsx
- client/src/user/leaderboard/Leaderboard.jsx
Ratings dependent leaderboard with platform filter and pagination
fixes #198
> Leaderboard for users 

- README.md
- package-lock.json
- package.json
Same changes as https://github.com/digitomize/digitomize/pull/208 for version2 branch.
> use postinstall script (version2 branch)

- client/src/components/HeroSection.jsx
- client/src/components/css/Card.css
- client/src/components/css/HeroSection.css
> Add a Hover/Transition Effect Over 'go to contest button'!!

- .all-contributorsrc
> Update .all-contributorsrc with new contributors

- backend/index.js
**Error Handling**:
Added handlers for uncaught exceptions to provide proper logging and gracefully shut down the server.
Added handlers for unhandled promise rejections to ensure server stability and prevent silent failures.
Added middleware which triggers when the entered route is wrong 
Fixes #215 
> EnhancedErrorHandling#215

- backend/users/services/setUser.js
Fixed the issue where User register with already used username and mongoDB rejects it.
How is it fiexd?
1. Check if the same username exist in mongoDB.
2. If yes, then assigned username with uid.
3. Else keep username as it is.
Fixes #218 
> [FIXED BUG] Duplicate username rejection by mongoDB

- client/src/components/MobNav.jsx
- client/src/components/NewNavbar.jsx
- client/src/user/dashboard/UserDashboard.jsx
Removed *redundant code*, by refactoring navbar files using, **Array of objects** and and **Array.map()** method. 
Fixes #186
> [Refactor] Enhanced navbar components with array of objects and map

- client/src/components/NewNavbar.jsx
- client/src/user/components/DashboardNavbar.jsx
- client/src/user/components/MobileNav.jsx
Removed redundant code, by refactoring navbar files using, **Array of objects** and and **Array.map()** method.
Fixes #186
> [REFACTOR] MobNav and DashboardNav refactored

- client/src/App.jsx
- client/src/components/Login.jsx
- client/src/components/MobNav.jsx
- client/src/components/NewNavbar.jsx
- client/src/user/UserHeader.jsx
- client/src/user/components/DashboardNavbar.jsx
- client/src/user/components/MobileNav.jsx
- client/src/user/dashboard/UserDashboard.jsx
Changed all URLs from "/user/" to "/u/" to enhance the project structure and to maintain uniform URL pattern.
> [Enhancement] Changed all url from "/user/" to "/u/"

- client/package-lock.json
- client/package.json
- client/src/components/AuthButtons/GithubAuthButton.jsx
- client/src/components/AuthButtons/GoogleAuthButton.jsx
- client/src/components/HomePage2.jsx
- client/src/components/HomePage3.jsx
- client/src/components/Login.jsx
- client/src/components/NewHome.jsx
- client/src/components/NewNavbar.jsx
- client/src/components/ScrollToTop.jsx
- client/src/components/Signup.jsx
- client/src/components/Updates.jsx
- client/src/components/share_model.jsx
- client/src/user/dashboard/UserDashPersonal.jsx
- client/src/user/dashboard/UserDashboard.jsx
Also fixed code redundancy and inconsistency
> Added components for auth buttons

- client/src/components/error-page.jsx
- client/src/user/Profile/components/PlatformRatings.jsx
- client/src/user/Profile/components/UserCard.jsx
- client/src/user/Profile/pages/ProfileRatingsPage.jsx
- client/src/user/dashboard/UserDashRatings.jsx
- client/tailwind.config.js
> Ratings page UI changed

- backend/services/discord-webhook/updateAccount.js
- backend/users/controllers/AdminUserController.js
- backend/users/controllers/authController.js
- backend/users/controllers/userDashboardController.js
- backend/users/controllers/userProfileController.js
- backend/users/controllers/userUpdateController.js
- backend/users/models/User.js
- backend/users/services/setUser.js
- client/src/App.jsx
- client/src/user/Profile/NewUserProfile.jsx
- client/src/user/dashboard/UserDashPersonal.jsx
Description
Added Resume Modal to the Resume Section in Dashboard.
Type of change
✔️Enhanced code (breaking change which enhanced codeblocks)
Checklist:
✔️My code follows the style guidelines of this project
✔️I have performed a self-review of my code
❌My changes generate no new warnings
✔️Any dependent changes have been merged and published in modules
Warnings!!:
Before merging we have to create personal_data.resume to remove the generated warnings.
> Added Resume Modal to the Resume Section in Dashboard

- client/src/components/ScrollToTop.jsx
changing ScrollToTop component bottom from 30px to 20px to align with the Chat component
> Fixing Realingment of ScrollToTop Component

- client/index.html
- client/src/components/share_model.jsx
#279 
Changed twitter icon to X
> Changed twitter logo

- backend/package-lock.json
- backend/package.json
- backend/users/controllers/cloudinaryUploadController.js
- backend/users/routes/userRoutes.js
- client/api.js
- client/src/components/ImageUploader.jsx
- client/src/user/dashboard/UserDashPersonal.jsx
- package.json
Added feature for users to upload their profile pictures from the client side seamlessly using `Cloudinary`. The pictures will be directly uploaded from the users device after Authentication and signing of the picture to cloudinary resulting is less load on our servers and better user experience 
Fixes #241 
Loom Video
[Watch the Loom video here](https://www.loom.com/share/5452e7b16e4a4d6b874decaf6e435f51?sid=6a29a302-722d-4d80-8aa1-afc59a65927c)
For this feature to work you need to do the following things
- create a Cloudinary account
- Go to the dashboard and access `API secret`, `API Key` and `Cloud Name`
- add VITE_REACT_APP_CLOUDINARY_API_SECRET to backend .env file and populate it with the respective values
- add VITE_REACT_APP_CLOUDINARY_API_KEY, …
> Feat: cloudinary integration to support profile pic upload

- client/src/components/css/IndividualCard.css
> fix: flex-end; (suggested by vite)

- client/src/components/globals/Footer.jsx
- client/src/components/globals/ScrollToTop.jsx
- Increased padding around the footer elements for improved aesthetics and readability.
- Added transition duration to the scroll button appearance, preventing abrupt visibility changes upon scrolling to the bottom.
>  Changes to footer and scrollToTop button

- client/src/user/leaderboard/components/Rank.jsx
when leaderboard fetching data of the user it shows "(@undefined)" as username.
Now it shows "Loading..." instead of undefined while fetching data.
> Fix Issue #323

- client/src/components/globals/Filter.jsx
> Fix The Content Not Aligned Properly ,Add Contest Icons in Tags

- client/src/user/leaderboard/components/Rank.jsx
Fixes: #336 
Added a skeleton when the ranks are loading.
> Added skeleton for ranks loading

- client/src/components/About.jsx
Fixed the responsiveness of about page.
fixes #325
> Added Responsiveness

- .husky/pre-commit
- client/src/components/IndividualCard.jsx
- client/src/components/css/IndividualCard.css
- client/src/components/globals/IndividualCard.jsx
- Individual card text change
- about page cards re-size
> Minor changes

- PR_GUIDELINES.md
This PR addresses the conflicting instructions in the repository regarding which branch PRs should be submitted against. The current guidelines have contradictory statements, causing confusion among contributors. This PR aims to clarify the correct branch for PR submissions.
This PR resolves issue #[976] (Conflicting Pull Request Guidelines). Edited the documentation to only submit PRs against the `main` branch.
- Updated the PR_GUIDELINES.md to specify the correct branch of PR submissions
Please review the updated guidelines and confirm that the specified branch for PR submissions is correct. This will help in maintaining a clear and consistent contribution process.
> fix: conflicts-PR_GUIDELINES
